{% set name = "tiledbsoma" %}
{% set version = "1.1.2" %}
{% set sha256 = "7c10b39df50b3bf90eaa2237fcfdca349b2d6efdecaef81103979930edd5b1c8" %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://github.com/single-cell-data/TileDB-SOMA/archive/{{ version }}.tar.gz
  url: https://github.com/single-cell-data/TileDB-SOMA/archive/64b262c1336c0498ff001d4180d0eb27d1d574cc.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win or linux32 or py2k]

outputs:
  - name: libtiledbsoma
    version: {{ version }}
    script: build-libtiledbsoma.sh  # [not win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make  # [not win]
      host:
        - tiledb 2.15.*
        - spdlog
        - fmt
      run:
        - tiledb 2.15.*
        - spdlog
        - fmt
  - name: tiledbsoma-py
    version: {{ version }}
    script: build-tiledbsoma-py.sh
    build:
    requirements:
      build:
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - libtiledbsoma {{ version }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - anndata
        - pandas
        - pyarrow 9.0.*
        - python
        - scipy
        - anndata
        - tiledb-py 0.21.*
        - typing-extensions
        - numba
        - attrs
        - somacore 1.0.*
        - scanpy 1.9.*
    imports:
      - tiledbsoma
    test:
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"

about:
  home: http://tiledb.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'TileDB-SOMA API'
  description: 'Python API for efficient storage and retrieval of single-cell data using TileDB'
  doc_url: https://docs.tiledb.com/
  dev_url: https://github.com/single-cell-data/TileDB-SOMA

extra:
  recipe-maintainers:
    - johnkerl
    - gspowley
    - shelnutt2
    - mlin
